### ISSUE TITLE
Chapter 2 

### ISSUE THREAD

**Issue by dshelldhillon** [EdwinTh/ADSwR#2]
Hi Edwin, 
I recently started reading your book and it serves as an excellent introduction to the agile workflow for someone like me (recent grad, thrown into a big pool of clients to work for).  

I don't know what the best way to fix typos etc is, but as you mentioned, opening an issue is one way.  So opening a chapter 2 issue where I'll comment my suggestions on typos etc.  

Hope that's ok!

**Comment by dshelldhillon** [comment]
section 2.1, line 2, `Rather it is a set of beliefs` instead of believes.

**Comment by EdwinTh** [comment]
Thank you so much! This works fine, I'll fix it right away. Alternatively, you could als do a pull request, you can even do it directly in github. Open te file you want to change in the Code section and then click edit in the top right. You can then file the PR at the bottom of the screen.
<img width="332" alt="Screenshot 2019-08-01 at 15 53 12" src="https://user-images.githubusercontent.com/7958036/62299192-cb358880-b474-11e9-9f38-4cd56696eede.png">
