### ISSUE TITLE
Pdf and epub files not available

### ISSUE THREAD

**Issue by datarttu** [EdwinTh/ADSwR#7]
Hi,

I find this book really promising and would like to read it on my e-reader as well! However, downloading the pdf [`https://edwinth.github.io/ADSwR/_main.pdf`](https://edwinth.github.io/ADSwR/_main.pdf) or epub [`https://edwinth.github.io/ADSwR/_main.epub`](https://edwinth.github.io/ADSwR/_main.epub) file does not work at the moment but results in an `404 File not found` error page. Luckily I was able to find these files in the repo under the [_book](https://github.com/EdwinTh/ADSwR/tree/master/_book) directory (where the rendered html files are located as well), but I think one should be able to find them via the download button of the online version too?

Thanks once more for this awesome content!

**Comment by EdwinTh** [comment]
Thanks for letting me know! I just focused on the online version during development, with continuous integration it was automatically built from github pushes. I will look into this asap.

**Comment by EdwinTh** [comment]
Done!
